# Generated by Django 3.2.16 on 2023-01-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20230120_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='wiki_link',
            field=models.URLField(),
        ),
    ]
